#!/bin/sh

gperf_input='src/char_ref_gperf.gperf'
gperf_output='src/char_ref_gperf.c'
max_entity_len=0

cd "$(dirname "$0")"

cat > "$gperf_input" <<EOF
%{
#include "char_ref.h"
%}
%pic
%includes
%language=ANSI-C
%define lookup-function-name gumbo_named_char_ref_find
%define hash-function-name gumbo_named_char_ref_hash
%struct-type
%compare-lengths
%omit-struct-type
%readonly-tables
struct GumboNamedCharRef;
%%
EOF

while read -r entity_entry; do
	name_start="${entity_entry#*\"}"
	name_full="${name_start%%\"*}"
	name="${name_full#&}"
	name_len=${#name}

	if [ "$name_len" -gt "$max_entity_len" ]; then
		max_entity_len="$name_len"
	fi

	codepoints_start="${entity_entry#*[}"
	codepoints="${codepoints_start%%]*}"

	[ "$codepoints" = "${codepoints#*,}" ] && codepoints="${codepoints}, -1"

	echo "${name}, ${codepoints}"
done >> "$gperf_input" <<EOF
$(grep codepoints doc/entities.json)
EOF
# EOF trick is used to avoid running a loop in a subshell
# doc/entities.json come from https://html.spec.whatwg.org/entities.json

echo '%%' >> "$gperf_input"

echo Started gperf code generation. This may take a while...
echo '/* DO NOT EDIT! AUTOGENERATED VIA genentities.sh */' > "$gperf_output"
echo >> "$gperf_output"
gperf -m 1000 -F ', -1, -1' < "$gperf_input" >> "$gperf_output"

sed -i "s/GUMBO_NAMED_CHAR_REF_MAX_LEN =.*/GUMBO_NAMED_CHAR_REF_MAX_LEN = $max_entity_len/" src/char_ref.c
